### ISSUE TITLE
Approximate equality won't compile

### ISSUE THREAD

**Issue by andrej-petrovic** [funkwerk/dshould#6]
I'm trying to migrate my tests to dshould, but I'm having trouble figuring out how to use `approximately`. I've tried the following:

`a.should.approximately.equal(b, error=1.0e-5);` (as the readme suggests).
`a.should.approximately.equal(b, error=error(1.0e-5));` (using the error() function from dshould)
`a.should.approximately.equal(b, error(1.0e-5));`
`a.should.approximately.equal(b, 1.0e-05);`
`a.should.approximately.equal(b);`

All of these fail to compile for one reason or another. I've also tried changing the order of words e.g. `should.be.approximately`, `should.be.approximately.equal`, etc. but nothing I've tried so far works. 

Usually the error is along the lines of:

```
Error: template dshould.equal cannot deduce function from argument types !()(ShouldType!(float delegate() pure @safe, ["approximately"]), float, ErrorValue), candidates are:
...
```

Or something similar.

Thanks in advance for any guidance

**Comment by FeepingCreature** [comment]
A user! Jubilations!

`a.should.approximately.equal(b, error = 1.0e-5)` should work. (By the unittests.) If it doesn't, could you give me a reproduction with that syntax?

**Comment by andrej-petrovic** [comment]
I wrote this:
```
1.0f.should.approximately.equal(2.0f, error = 1.0e-5f);
```
And I get this error:
```
Error: template dshould.equal cannot deduce function from argument types !()(ShouldType!(float delegate() pure @safe, ["approximately"]), float, ErrorValue), candidates are:
<snip>\dub\packages\dshould-1.1.0\dshould\src\dshould\package.d(18,13):        equal(Should, T)(Should should,
T value, Fence _ = Fence(), string file = __FILE__, size_t line = __LINE__)
<snip>\dub\packages\dshould-1.1.0\dshould\src\dshould\package.d(43,13):        equal(Should)(Should should)
```
I'm on dmd 2.088 and also getting some weird deprecation warning in phobos, might be causing problems but I doubt it. I'll update to 2.089 and see if that helps. EDIT: Nope, deprecation's gone but the dshould.equal issue is still there

Honored to be the first issue submitter ;P Didn't know whether to use this or fluent-asserts, but I chose this because fluent-asserts has tons of dependencies which makes builds take a lot longer.

**Comment by andrej-petrovic** [comment]
I took a closer look at a code and figured out working syntax:
```
a.should.be.approximately(b, error = 1.0e-5f);
```

BTW how did you make the `error = ` syntax work? Does D have named arguments? Or is it somehow calling error() and then assigning a float to the resulting ErrorValue?

**Comment by FeepingCreature** [comment]
It's a hack on the property syntax. You can write property setters by writing a method that takes a parameter:

```
struct S {
  int value_;
  int value() { return value_; }
  void value(int value) { this.value_ = value; }
}
S s;
s.value = 5; // s.value(5);
assert(s.value == 5); // assert(s.value() == 5);
```
The thing is that this also works for freestanding functions. So `error =` calls `error(float)` as a module-level setter, and the `ErrorValue` type indicates that the value came out of an `error =` call. :)
